# Reference:
#   - https://cirrus-ci.org/guide/writing-tasks/
#   - https://cirrus-ci.org/guide/linux/
#   - https://hub.docker.com/_/gcc/
#   - https://hub.docker.com/_/python/

#
# Global defaults.
#
container:
  image: gcc:latest
  cpu: 2
  memory: 4G


env:
  # Maximum cache period (in weeks) before forcing a new cache upload.
  CACHE_PERIOD: "2"
  # Increment the build number to force new mambaforge cache upload.
  MAMBA_CACHE_BUILD: "0"
  # Increment the build number to force new cf-units cache upload.
  CFUNITS_CACHE_BUILD: "0"
  # Base environment conda packages to be installed
  MAMBA_CACHE_PACKAGES: "pip conda-lock"


#
# Linting
#
lint_task:
  auto_cancellation: true
  container:
    image: python:latest
    cpu: 2
    memory: 4G
  name: "${CIRRUS_OS}: linting"
  lint_script:
    - python -m pip install --retries 3 pre-commit
    - pre-commit run --all-files black
    - pre-commit run --all-files flake8
    - pre-commit run --all-files isort


#
# Testing (Linux)
#
linux_task:
  auto_cancellation: true
  matrix:
    env:
      PY_VER: "3.7"
    env:
      PY_VER: "3.8"
    env:
      PY_VER: "3.9"
      COVERAGE: "codecov"
  name: "${CIRRUS_OS}: py${PY_VER}"
  env:
    PATH: ${HOME}/mambaforge/bin:${PATH}
  mamba_cache:
    folder: ${HOME}/mambaforge
    fingerprint_script:
      - wget --quiet https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-x86_64.sh -O mambaforge.sh
      - echo "${CIRRUS_OS} $(sha256sum mambaforge.sh)"
      - echo "${MAMBA_CACHE_PACKAGES}"
      - echo "$(date +%Y).$(expr $(date +%U) / ${CACHE_PERIOD}):${MAMBA_CACHE_BUILD}"
    populate_script:
      - bash mambaforge.sh -b -p ${HOME}/mambaforge
      - conda config --set always_yes yes --set changeps1 no
      - conda config --set show_channel_urls True
      - conda config --add channels conda-forge
      - conda install --quiet --name base ${MAMBA_CACHE_PACKAGES}
  check_script:
    - conda info --all
    - conda list --name base
  cfunits_cache:
    folder: ${HOME}/mambaforge/envs/py${PY_VER}
    fingerprint_script:
      - echo "${CIRRUS_OS} py${PY_VER} tests"
      - echo "$(date +%Y).$(expr $(date +%U) / ${CACHE_PERIOD}):${CFUNITS_CACHE_BUILD}"
      - cat ${CIRRUS_WORKING_DIR}/requirements/py$(echo ${PY_VER} | tr -d ".").yml
    populate_script:
      - conda-lock --mamba --platform linux-64 --file ${CIRRUS_WORKING_DIR}/requirements/py$(echo ${PY_VER} | tr -d ".").yml
      - mamba create --name py${PY_VER} --quiet --file conda-linux-64.lock
      - cp conda-linux-64.lock ${HOME}/mambaforge/envs/py${PY_VER}
  test_script:
    - cat ${HOME}/mambaforge/envs/py${PY_VER}/conda-linux-64.lock >&2
    - source ${HOME}/mambaforge/etc/profile.d/conda.sh >/dev/null 2>&1
    - conda activate py${PY_VER} >/dev/null 2>&1
    - CYTHON_COVERAGE=1 pip install --no-deps --editable .
    - pytest --cov-report=xml --cov
    - ${COVERAGE}
