# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
        # Prevent giant files from being committed.
    -   id: check-added-large-files
        # Check whether files parse as valid Python.
    -   id: check-ast
        # Check for file name conflicts on case-insensitive filesytems.
    -   id: check-case-conflict
        # Check for files that contain merge conflict strings.
    -   id: check-merge-conflict
        # Check for debugger imports and py37+ `breakpoint()` calls in Python source.
    -   id: debug-statements
        # Don't commit to main branch.
    -   id: no-commit-to-branch

-   repo: https://github.com/aio-libs/sort-all
    rev: v1.2.0
    hooks:
    -   id: sort-all
        types: [file, python]

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.1.5"
    hooks:
    # Run the linter
    -   id: ruff
        types: [file, python]
        args: [--fix]
    # Run the formatter.
    -   id: ruff-format
