version: 2

build:
  os: ubuntu-20.04
  tools:
    python: mambaforge-4.10
  jobs:
    post_checkout:
      - git fetch --unshallow
      - git fetch --all

conda:
  environment: requirements/cf-units.yml

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

python:
  install:
    - method: pip
      path: .
