version: 2

build:
    image: latest

conda:
    environment: requirements/cf-units.yml

sphinx:
    configuration: doc/source/conf.py
    fail_on_warning: false

python:
    install:
        - method: setuptools
          path: .
