version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "latest"
  jobs:
    create_environment:
      # pixi is endorsed by Read the Docs:
      #  https://docs.readthedocs.com/platform/stable/build-customization.html#install-dependencies-with-pixi
      - asdf plugin add pixi
      - asdf install pixi latest
      - asdf global pixi latest
    post_checkout:
      # The SciTools/cf-units repository is shallow i.e., has a .git/shallow,
      # therefore complete the repository with a full history in order
      # to allow setuptools-scm to correctly auto-discover the version.
      - git fetch --unshallow
      - git fetch --all
    pre_install:
      # Need to stash any local changes that Read the Docs makes so that
      #  setuptools_scm can generate the correct cf-units version.
      - git stash
    install:
      - pixi install --frozen --environment docs
    post_install:
      # Restore any local changes stashed earlier, if there were any.
      - if git stash list | grep .; then git stash pop; fi
    build:
      html:
        - pixi run --frozen --environment docs readthedocs

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false
