version: 2

build:
  os: ubuntu-20.04
  tools:
    python: mambaforge-4.10
  jobs:
    post_checkout:
      # reference: https://github.com/SciTools/cf-units/pull/272
      # perform a "git fetch --unshallow" when the cf-units repo
      # becomes incomplete i.e., there is a .git/shallow.
      - git fetch --all
    pre_install:
      # create a "common" link to the underlying rtd conda environment,
      # which maybe named "latest", "stable" or the cf-units version
      - ln -s ${CONDA_ENVS_PATH}/${CONDA_DEFAULT_ENV} ${CONDA_ENVS_PATH}/common

conda:
  # NOTE: the activation script for this environment does not get run.
  #  Therefore, the UDUNITS2 environment variables are not set.
  #  They are instead set via the RTD dashboard (not yet possible via this
  #  configuration file - readthedocs/readthedocs.org#6311).
  environment: requirements/cf-units.yml

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

python:
  install:
    - method: pip
      path: .
