version: 2

build:
  os: ubuntu-24.04
  tools:
    python: mambaforge-4.10
  jobs:
    post_checkout:
      # The SciTools/cf-units repository is shallow i.e., has a .git/shallow,
      # therefore complete the repository with a full history in order
      # to allow setuptools-scm to correctly auto-discover the version.
      - git fetch --unshallow
      - git fetch --all
    pre_install:
      # create a "common" link to the underlying rtd conda environment,
      # which maybe named "latest", "stable" or the cf-units version
      - ln -s ${CONDA_ENVS_PATH}/${CONDA_DEFAULT_ENV} ${CONDA_ENVS_PATH}/common
      # Need to stash the local changes that Read the Docs makes so that
      #  setuptools_scm can generate the correct cf-units version.
      - git stash
    post_install:
      - git stash pop

conda:
  # NOTE: the activation script for this environment does not get run.
  #  Therefore, the UDUNITS2 environment variables are not set.
  #  They are instead set via the RTD dashboard (not yet possible via this
  #  configuration file - readthedocs/readthedocs.org#6311).
  environment: requirements/cf-units.yml

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

python:
  install:
    - method: pip
      path: .
