[build-system]
# Defined by PEP 518
requires = [
  "setuptools>=45",
  "setuptools_scm[toml]>=7.0",
  "wheel",
  "numpy",
  "Cython>=3.0"
]
# Defined by PEP 517
build-backend = "setuptools.build_meta"

[tool.coverage.run]
branch = true
plugins = [
    "Cython.Coverage"
]
include = [
    "cf_units/*"
]
omit = [
    "setup.py",
    "cf_units/_version.py",
    "cf_units/etc/*",
    "cf_units/tests/*",
    "cf_units/_udunits2_parser/parser/*",
    "cf_units/_udunits2_parser/compile.py",
    ".eggs"
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if __name__ == .__main__.:"
]

[tool.pytest.ini_options]
addopts = "-ra -v --doctest-modules"
doctest_optionflags = "NORMALIZE_WHITESPACE ELLIPSIS NUMBER"
minversion = "6.0"
testpaths = "cf_units"

[tool.setuptools_scm]
write_to = "cf_units/_version.py"
local_scheme = "dirty-tag"

[tool.black]
line-length = 79
target-version = ["py310", "py311", "py312"]
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | _version.py
)
'''

[tool.isort]
known_first_party = "cf_units"
line_length = 79
profile = "black"
skip_gitignore = "True"
verbose = "False"

[tool.repo-review]
# These are a list of the currently failing tests:
ignore = [
  "PY005",  # Has tests folder
  "PP003",  # Does not list wheel as a build-dep
  "PP304",  # Sets the log level in pytest
  "PP305",  # Specifies xfail_strict
  "PP306",  # Specifies strict config
  "PP307",  # Specifies strict markers
  "PP309",  # Filter warnings specified
  "GH104",  # Use unique names for upload-artifact
  "GH212",  # Require GHA update grouping
  "PC110",  # Uses black or ruff-format
  "PC140",  # Uses a type checker
  "PC160",  # Uses a spell checker
  "PC170",  # Uses PyGrep hooks (only needed if rST present)
  "PC180",  # Uses a markdown formatter
  "PC190",  # Uses Ruff
  "PC901",  # Custom pre-commit CI message
  "MY100",  # Uses MyPy (pyproject config)
  "RF001",  # Uses RUFF
]
