[build-system]
# Defined by PEP 518
requires = [
  "setuptools>=45",
  "setuptools_scm[toml]>=7.0",
  "wheel",
  "oldest-supported-numpy",
  "Cython"
]
# Defined by PEP 517
build-backend = "setuptools.build_meta"

[tool.coverage.run]
branch = true
plugins = [
    "Cython.Coverage"
]
include = [
    "cf_units/*"
]
omit = [
    "setup.py",
    "cf_units/_version.py",
    "cf_units/etc/*",
    "cf_units/tests/*",
    "cf_units/_udunits2_parser/parser/*",
    "cf_units/_udunits2_parser/compile.py",
    ".eggs"
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if __name__ == .__main__.:"
]

[tool.pytest.ini_options]
addopts = "-ra -v --doctest-modules"
doctest_optionflags = "NORMALIZE_WHITESPACE ELLIPSIS NUMBER"
minversion = "6.0"
testpaths = "cf_units"

[tool.setuptools_scm]
write_to = "cf_units/_version.py"
local_scheme = "dirty-tag"

[tool.black]
line-length = 88
target-version = ["py38", "py39", "py310", "py311"]
include = '\.pyi?$'

[tool.ruff]
line-length = 88
target-version = "py38"
select = [
    # pyflakes
    "F",
    # pycodestyle
    "E",
    "W",
    # flake8-bugbear
    "B",
    # flake8-comprehensions
    "C4",
    # isort
    "I",
    # pyupgrade
    "UP",
]
ignore = ["B904", "F403", "F405"]

[tool.ruff.isort]
force-sort-within-sections = true
known-first-party = ["cf_units"]

[tool.ruff.mccabe]
max-complexity = 22

[tool.ruff.pydocstyle]
convention = "numpy"
