# Reference
#    - https://github.com/actions/checkout

name: ci-manifest

on:
  pull_request:
    branches:
      - "*"

  push:
    branches-ignore:
      - "conda-lock-auto-update"
      - "pre-commit-ci-update-config"
      - "dependabot/*"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  manifest:
    name: "check-manifest"
    uses: scitools/workflows/.github/workflows/ci-manifest.yml@2023.04.3
